# -*- coding: utf-8 -*-
"""fraud_risk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gUJfKUkA6i7krgYJlDmF7yOcoTQ8OFmd

# <font color = 'BlueViolet'>**IA e Segurança**
## Análise de risco de fraudes transacionais </font>

### Sobre o dataset:
- O dataset contem dados de transações bancárias (cash-in e out, débito, pagamento e transferência)
- Totalizando **3713576 transações**.
- Destas, **336788** são fraudes (9.07%).
### Importante:
- Vemos que o dataset é altamente desbalanceado, com uma baixíssima porporção de fraudes (classe positiva). Neste caso, não é recomendado usar uma matriz de confusão por não representar uma medida significativa de performance em modelos desbalanceados.
- Todos os valores são numéricos, sem dados de localidade ou data e hora da transação.

### Dados:
- **Amount**: Valor da transação.
- **isFraud**: Indica se a transação é **legítima (0)** ou  **fraude (1)**.

## 1. Análises iniciais

### Bibliotecas utilizadas:
"""

"""
API Flask:
"""

from flask import Flask, request, jsonify
import joblib  # para carregar modelo treinado
# Importe suas funções do notebook aqui

app = Flask(__name__)

@app.route('/predict', methods=['POST'])
def predict_fraud():
    data = request.json.get('data', [])
    if not data:
        return jsonify({'error': 'Dados não fornecidos'}), 400
    
    df = pd.DataFrame(data)
    # Aplique pré-processamento do notebook (scaling, remoção outliers, etc.)
    # predicao = model.predict(df)
    
    risk_level = 'high' if len(df[df['isFraud'] == 1]) > 0 else 'low'
    return jsonify({
        'riskLevel': risk_level,
        'analysis': 'Análise baseada no modelo LogisticRegression/RandomForest',
        'frauds_detected': int(df['isFraud'].sum())
    })

if __name__ == '__main__':
    app.run(port=5000, debug=True)
#  Manipulação e visualização de dados
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import sidetable as stb

#  Machine Learning
# from sklearn.preprocessing import RobustScaler
# from sklearn.model_selection import train_test_split
# from sklearn.model_selection import StratifiedKFold


# from sklearn.linear_model import LogisticRegression
# from sklearn.ensemble import RandomForestClassifier


# from sklearn.model_selection import cross_val_score

"""### Carregar o dataset e visualizar os valores:"""

df = pd.read_csv('New_Dataset.csv')
df.head()

# Colunas do dataset
df.columns.tolist()

"""### Tamanho da base de dados:"""

print("O dataset possui {} linhas e {} colunas.".format(df.shape[0], df.shape[1]))

"""### <font color = 'BlueViolet'>Como visto, temos um registros de 3713576 transações, com 14 colunas.</font>

### Visão geral de organização dos dados:
"""

df.info()

"""### <font color = 'BlueViolet'>Não temos valores nulos, então não será necessário se preocupar em substitui-los para não haver distorções.</font>

### Visão geral de estatísticas descritivas:
"""

df.describe(include='float')

"""<font color = 'BlueViolet'>
- O valor médio das transações é de 25.4492, com um desvio padrão maior que a média (57.0202). Isso indica a presença de outliers.
</font>
"""

df[df['isFraud']==1].shape[0]

df[df['isFraud']==1].shape[0] / df.shape[0] * 100

df['amount'].sum()

df.groupby(['isFraud']).agg({'amount': ['sum']}).stb.pretty()

df[df['action__CASH_IN'] == 1].groupby(['action__CASH_IN']).agg({'amount': ['sum']}).stb.pretty()

df[df['action__CASH_OUT'] == 1].groupby(['action__CASH_OUT']).agg({'amount': ['sum']}).stb.pretty()

df[df['action__DEBIT'] == 1].groupby(['action__DEBIT']).agg({'amount': ['sum']}).stb.pretty()

df[df['action__PAYMENT'] == 1].groupby(['action__PAYMENT']).agg({'amount': ['sum']}).stb.pretty()

df[df['action__TRANSFER'] == 1].groupby(['action__TRANSFER']).agg({'amount': ['sum']}).stb.pretty()

"""## 2. Análise exploratória e análises gráficas

### Distribuição de fraudes vs. transações legítimas:
"""

# Distribuição das classes
plt.figure(figsize=(12, 6))
ax = sns.countplot(x='isFraud', data=df)
ax.set_title('Distribuição de Classes\n (Não-fraude: 0 | Fraudes: 1)', fontsize=20)
ax.set_xlabel('Classe', fontsize=16)
ax.set_ylabel('Contagem', fontsize=16)
plt.show()

"""### <font color = 'BlueViolet'> Essa enorme predominância de transações que não são fraudes cria um modelo que "assume" que a maior parte das transações é legítima. Como isso não necessariamente é verdade, precisamos que o modelo detecte padrões que sinalizam atividade suspeita. </fonte>"""
